### ISSUE TITLE
 uninitialized constant RailsLocaleDetection (NameError)

### ISSUE THREAD

**Issue by Rovel** [mateomurphy/rails_locale_detection#10]
I added a initializer as the README.md intructs but I get the following error:

.../config/initializers/rails_locale_detection.rb:1:in `<top (required)>': uninitialized constant RailsLocaleDetection (NameError)
	from ../.rvm/gems/ruby-2.2.3/gems/railties-4.1.13/lib/rails/engine.rb:648:in `block in load_config_initializer'

#config/initializers/rails_locale_detection.rb

RailsLocaleDetection.config do |config|
  config.locale_expiry = 3.months
  config.set_default_url_option = :always # valid values are true, false, :always, :never and :explicity
  config.detection_order = [:param, :user, :request]
  config.automatically_detect = true
  config.locale_key = :locale
end

**Comment by mateomurphy** [comment]
Please try the latest master from github and let me know if it fixes this issue

**Comment by Rovel** [comment]
I've updated the gem and the rails to match 4.2.4 but even after the update it still throwing the uninitialized constant error, can I be missing something? a great update to the gem would be the initializer is generated as the gem is installed...

Error:
config/initializers/rails_locale_detection.rb:1:in `<top (required)>': uninitialized constant RailsLocaleDetection (NameError)
	from /Users/.../.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'

**Comment by mateomurphy** [comment]
It might be that you don't have the latest commits, try the following in your Gemfile

 `gem 'rails_locale_detection', git: 'git@github.com:mateomurphy/rails_locale_detection.git', ref: '3997fc1c4b5d0b557e7e8cb77aaa0173b572baf4'`

If that doesn't work, try simply putting `require 'rails_locale_detection'` at the top of the initializer file

**Comment by Rovel** [comment]
Mateo, after pointing the commits to the gemfile the initializer is working fine!
Thanks!

**Comment by Rovel** [comment]
I've tried to git push to a staging remote and got permission denied to use your latest commit:
Fetching git@github.com:mateomurphy/rails_locale_detection.git
remote:        Host key verification failed.
remote:        fatal: Could not read from remote repository.
remote:        Please make sure you have the correct access rights
remote:        and the repository exists.
remote:        Retrying git clone 'git@github.com:mateomurphy/rails_locale_detection.git' "/tmp/build_38da50e2f23f7d4d048e4537df2ed94d/vendor/bundle/ruby/2.2.0/cache/bundler/git/rails_locale_detection-78d7aa69601493150e33a8ce8ff64a36903bea9a" --bare --no-hardlinks --quiet due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:mateomurphy/rails_locale_detection.git' "/tmp/build_38da50e2f23f7d4d048e4537df2ed94d/vendor/bundle/ruby/2.2.0/cache/bundler/git/rails_locale_detection-78d7aa69601493150e33a8ce8ff64a36903bea9a" --bare --no-hardlinks --quiet` in directory /tmp/build_38da50e2f23f7d4d048e4537df2ed94d has failed.

**Comment by mateomurphy** [comment]
I've pushed a new release to ruby gems, you should be able to use that now `gem 'rails_locale_detection', '~> 2.0.0'`

**Comment by Rovel** [comment]
working fine, thanks for the help!
