### ISSUE TITLE
Update http_accept_language gem dependency

### ISSUE THREAD

**Issue by tmaier** [mateomurphy/rails_locale_detection#9]
Current version of [http_accept_language](http://rubygems.org/gems/http_accept_language) is 2.0.1.
`rails_locale_detection` depends on version 1.0.2 from 2011.

Here's the diff of the two versions: https://github.com/iain/http_accept_language/compare/540b750c916f818c79f935c930d44bdead16c5ad...v2.0.1

The biggest change seems to be that you have to call `http_accept_language.preferred_language_from ` instead of `request.preferred_language_from `.

**Comment by mateomurphy** [comment]
2.0 is now released and http_accept_language is now updated

**Comment by tmaier** [comment]
Thanks
